language: ruby
rvm: 2.3.1
sudo: false

before_install:
 - gem install hiptest-publisher
 - "hiptest-publisher -c cucumber.conf  --only=features,step_definitions --test-run-id=162380"

script:
 - bundle exec cucumber --format junit --out results

after_script:
  - hiptest-publisher -c cucumber.conf  --push="results/*.xml" --test-run-id=162380
